import { db } from '@/db';
import { slots } from '@/db/schema';

async function main() {
    const sampleSlots = [
        // Floor 1 (parkingAreaId 1, floorId 1) - 20 slots
        { floorId: 1, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 13, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 14, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 15, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 16, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 17, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 18, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 19, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 1, slotNumber: 20, status: 'booked', createdAt: new Date('2024-01-15').toISOString() },

        // Floor 2 (parkingAreaId 1, floorId 2) - 20 slots
        { floorId: 2, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 13, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 14, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 15, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 16, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 17, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 18, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 19, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 2, slotNumber: 20, status: 'booked', createdAt: new Date('2024-01-15').toISOString() },

        // Floor 3 (parkingAreaId 1, floorId 3) - 20 slots
        { floorId: 3, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 13, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 14, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 15, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 16, status: 'available', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 17, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 18, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 19, status: 'occupied', createdAt: new Date('2024-01-15').toISOString() },
        { floorId: 3, slotNumber: 20, status: 'booked', createdAt: new Date('2024-01-15').toISOString() },

        // Floor 4 (parkingAreaId 2, floorId 4) - 15 slots
        { floorId: 4, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 13, status: 'occupied', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 14, status: 'occupied', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 4, slotNumber: 15, status: 'booked', createdAt: new Date('2024-01-16').toISOString() },

        // Floor 5 (parkingAreaId 2, floorId 5) - 15 slots
        { floorId: 5, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 13, status: 'occupied', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 14, status: 'occupied', createdAt: new Date('2024-01-16').toISOString() },
        { floorId: 5, slotNumber: 15, status: 'booked', createdAt: new Date('2024-01-16').toISOString() },

        // Floor 6 (parkingAreaId 3, floorId 6) - 25 slots
        { floorId: 6, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 13, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 14, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 15, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 16, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 17, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 18, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 19, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 20, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 21, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 22, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 23, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 24, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 6, slotNumber: 25, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },

        // Floor 7 (parkingAreaId 3, floorId 7) - 25 slots
        { floorId: 7, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 13, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 14, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 15, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 16, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 17, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 18, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 19, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 20, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 21, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 22, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 23, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 24, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 7, slotNumber: 25, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },

        // Floor 8 (parkingAreaId 3, floorId 8) - 25 slots
        { floorId: 8, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 13, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 14, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 15, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 16, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 17, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 18, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 19, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 20, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 21, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 22, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 23, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 24, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 8, slotNumber: 25, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },

        // Floor 9 (parkingAreaId 3, floorId 9) - 25 slots
        { floorId: 9, slotNumber: 1, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 2, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 3, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 4, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 5, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 6, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 7, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 8, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 9, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 10, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 11, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 12, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 13, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 14, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 15, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 16, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 17, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 18, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 19, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 20, status: 'available', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 21, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 22, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 23, status: 'occupied', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 24, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },
        { floorId: 9, slotNumber: 25, status: 'booked', createdAt: new Date('2024-01-17').toISOString() },
    ];

    await db.insert(slots).values(sampleSlots);
    
    console.log('✅ Slots seeder completed successfully - 190 total slots created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});